#!/bin/bash

ipconfig getpacket en0 | grep 'yiaddr' | awk '{print$3}'

#
#	yiaddr is IP address assigned by DHCP server
#	chaddr is machine  MAC address
#	server_identifier is DHCP server's IP address
#
